//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : FreeMarkHandler.java
//  @ Date : 2015/5/9
//  @ Author : shanlin
//
//
package com.shanlin.demo.helper;

import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.io.Reader;
import java.io.StringWriter;
import java.io.Writer;
import java.util.Map;

import freemarker.template.Configuration;
import freemarker.template.Template;


public class FreemarkerParser {
    private static Template template = null;
    
    /**
     * 功能描述: <br>
     *
     * @param javaTemplate
     * @return the string that was parsed 
     */
    public static String parse(InputStream ins, Map<String, Object> model, Configuration configuration){
        Writer out = null;
        Reader reader = null;
        try {
            out = new StringWriter();
            
			reader = new InputStreamReader(ins,"utf-8");
			
            template = new Template(null, reader, configuration);
            template.process(model, out);
            
            return out.toString();
        } catch (Exception e) {
        	e.printStackTrace();
        }finally{
            try {
                if (out !=null) {
                    out.close();
                }
                if (reader != null) {
					reader.close();
				}
            } catch (IOException e) {
            	e.printStackTrace();
            }
        }
        
        return null;
    }
}
